### ISSUE TITLE
[FEATURE] Deploy Visualization EC2 Instance

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#146]
**Is your feature request related to a problem? Please describe.**
We've added an module for visualization ROS data on EC2 using NiceDCV. Add this to the ros-image-demo manifest to showcase how to configure and deploy the module

**Describe the solution you'd like**
- Add manifest to deploy the modules/visualization/dev-instance module

**Comment by dgraeber** [comment]
https://github.com/awslabs/autonomous-driving-data-framework/pull/143
