### ISSUE TITLE
[FEATURE] Add pipeline for training YoloV5 model

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#147]
*Is your feature request related to a problem? Please describe.*
The MLOps Modules allows us to do model training on AWS either via SageMaker or EKS. Add a sample training pipeline for training the model that is used by the object/lane detection pipelines to allow customers to improve the model over time. 

*Describe the solution you'd like*
- SageMaker Project Template that includes a SageMaker Pipeline to train the YoloV5 Model
- KubeFlow Project + Pipeline that includes the training pipeline for training the YoloV5 Model

**Comment by srinivasreddych** [comment]
@a13zen Is this still relevant?
