### ISSUE TITLE
[INVESTIGATION] OpenLineage support

### ISSUE THREAD

**Issue by srinivasreddych** [awslabs/autonomous-driving-data-framework#151]
Look into this blog post and supporting code to evaluate whether OpenLineage can be used in ADDF.

https://aws.amazon.com/blogs/big-data/automate-data-lineage-on-amazon-mwaa-with-openlineage/
https://github.com/aws-samples/aws-mwaa-openlineage

Focus on:

- which modules we currently have in ADDF that can be repurposed (ex. S3, VPC, EKS)
- which modules need to be created (ex. Redshift Serverless)
- which modules need to be modified, if any (ex MWAA and requirements) that MUST be backward compatible
- which compute to be used for Marques and OpenLineage (suggest EKS)

**Comment by dgraeber** [comment]
This was closed as there is not a way to move an `issue` back to a `draft` and this item needed grooming
