### ISSUE TITLE
[BUG] rosbag-webviz deploying issue

### ISSUE THREAD

**Issue by data0** [awslabs/autonomous-driving-data-framework#158]
**Describe the bug**
modules/demo-only/rosbag-webviz had errors deploying

**To Reproduce**
 - follow the ADDF deployment guide:
 - git clone --origin upstream --branch main https://github.com/awslabs/autonomous-driving-data-framework
 - ...
 - seedfarmer apply manifests/demo/deployment.yaml

**Expected behavior**
All selected modules deployed without issues

**Screenshots**
![rosbag-webviz](https://user-images.githubusercontent.com/13135401/215508350-c300b884-3bd0-411a-8127-fb9b9af2b461.jpg)

**Additional context**
It looks like a dependency issue in rosbag-webviz

[codeseeder-addf]:

[Container] 2023/01/30 13:50:19 Running command npm install
170 | npm ERR! code ERESOLVE
171 | npm ERR! ERESOLVE could not resolve
172 | npm ERR!
173 | npm ERR! While resolving: ts-jest@29.0.3
174 | npm ERR! Found: typescript@3.9.10
175 | npm ERR! node_modules/typescript
176 | npm ERR!   dev typescript@"~3.9.7" from the root project
177 | npm ERR!   peer typescript@">=2.7" from ts-node@9.1.1
178 | npm ERR!   node_modules/ts-node
179 | npm ERR!     dev ts-node@"^9.0.0" from the root project
180 | npm ERR!     peerOptional ts-node@">=9.0.0" from jest-config@29.3.1
181 | npm ERR!     node_modules/jest-config
182 | npm ERR!       jest-config@"^29.3.1" from @jest/core@29.3.1
183 | npm ERR!       node_modules/@jest/core
184 | npm ERR!         @jest/core@"^29.3.1" from jest@29.3.1
185 | npm ERR!         node_modules/jest
186 | npm ERR!         1 more (jest-cli)
187 | npm ERR!       1 more (jest-cli)
188 | npm ERR!
189 | npm ERR! Could not resolve dependency:
190 | npm ERR! peer typescript@">=4.3" from ts-jest@29.0.3
191 | npm ERR! node_modules/ts-jest
192 | npm ERR!   dev ts-jest@"^29.0.3" from the root project
193 | npm ERR!
194 | npm ERR! Conflicting peer dependency: typescript@4.9.4
195 | npm ERR! node_modules/typescript
196 | npm ERR!   peer typescript@">=4.3" from ts-jest@29.0.3
197 | npm ERR!   node_modules/ts-jest
198 | npm ERR!     dev ts-jest@"^29.0.3" from the root project
199 | npm ERR!
200 | npm ERR! Fix the upstream dependency conflict, or retry
201 | npm ERR! this command with --force, or --legacy-peer-deps
202 | npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
203 | npm ERR!
204 | npm ERR! See /root/.npm/eresolve-report.txt for a full report.
205 |  
206 | npm ERR! A complete log of this run can be found in:
207 | npm ERR!     /root/.npm/_logs/2023-01-30T13_50_19_881Z-debug-0.log
208 |  
209 | [Container] 2023/01/30 13:50:20 Command did not exit successfully npm install exit status 1
210 | [Container] 2023/01/30 13:50:20 Phase complete: INSTALL State: FAILED_WITH_ABORT
211 | [Container] 2023/01/30 13:50:20 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install. Reason: exit status 1
212

**Comment by data0** [comment]
Removal of "ts-jest": "^29.0.3" from autonomous-driving-data-framework/modules/demo-only/rosbag-webviz/package.json was enough to deploy the module. Is "ts-jest" mandatory module's functionality?

**Comment by dgraeber** [comment]
Looks like a bigger issue:
https://github.com/thymikee/jest-preset-angular/issues/1774
