### ISSUE TITLE
[BUG] OpenSearch Proxy Module breaks when using passwords with special characters

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#23]
**Describe the bug**
When using auto generated passwords from SecretsManager, the passwords may include special characters that unless properly escaped breaks the `/modules/demo-only/opensearch-proxy` module. 

**To Reproduce**
- Go SecretsManager and generate username and password complying to the module [README](https://github.com/awslabs/autonomous-driving-data-framework/blob/main/modules/demo-only/opensearch-proxy/README.md)
- Use the Automated password generation to include special characters, generate a password with `"` or `'` or `$`.
- Deploy the module
- Use EC2 Connect to ssh into machine 
- Check the cloud init logs  `cat /var/log/cloud-init-output.log`
- Grab the generated user-data script `curl http://169.254.169.254/latest/user-data >> user-data.txt`
- Due to the unescaped bash special characters the user-data script will fail and the proxy module will not bootstrap properly

**Expected behavior**
- Any password can be used and the user-data script and basic authentication should work

**Logs**

 /var/log/cloud-init-output.log

```bash
cloud-init v. 19.3-45.amzn2 running 'modules:final' at Wed, 03 Aug 2022 16:17:33 +0000. Up 62.60 seconds.
download: s3://<removed>-eu-central-1/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh to tmp/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh
/var/lib/cloud/instance/scripts/part-001: line 6: unexpected EOF while looking for matching `"'
Aug 03 16:17:35 cloud-init[3222]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [2]
Aug 03 16:17:35 cloud-init[3222]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Aug 03 16:17:35 cloud-init[3222]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
```

user-data.txt
```bash
#!/bin/bash
mkdir -p $(dirname '/tmp/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh')
aws s3 cp 's3://<removed>-eu-central-1/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh' '/tmp/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh'
set -e
chmod +x '/tmp/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh'
'/tmp/9db3c2c8b9cf8226e2576a982eac11f32c7e1bfcc97daa87d48d8c56a1b8dd65.sh' vpc-<removed>.eu-central-1.es.amazonaws.com foo [x1#x&"X-1.x1X(x}'X'X$]z=!lU'X;X[x
```
Note password above is only example generated by hand

**Comment by dgraeber** [comment]
So all we need to do is update the script that generates the pwd to restrict on those characters?

**Comment by JunjieTang-D1** [comment]
@dgraeber any update for this?

**Comment by dgraeber** [comment]
After reviewing this bug and the issues denoted, I cannot agree there is an issue.  The automated password generator script provided in autonomous-driving-data-framework/scripts/setup-secrets-example.sh explicitly has a flag that denotes `--exclude-punctuation`, and that is the only reference to any auto-generated password.  I am putting a note in the readme that we only support alpha-numeric characters in passwords for this module.
