### ISSUE TITLE
[BUG] - DDB-to-Opensearch Readme missing a parameter

### ISSUE THREAD

**Issue by dgraeber** [awslabs/autonomous-driving-data-framework#231]
The module `modules/integration/ddb-to-opensearch` is missing a parameter in the README - the `PRIVATE_SUBNET_IDS` (aka `private-subnet-ids`) is a required parameter but is not denoted.

Please add this parameter definition to the README of the module

**Comment by srinivasreddych** [comment]
This has been fixed internally. I will be bringing this change soon!
