### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cheefoo** [awslabs/autonomous-driving-data-framework#236]
**Describe the bug**
I was following the blog [here](https://aws.amazon.com/blogs/industries/develop-and-deploy-a-customized-workflow-using-autonomous-driving-data-framework-addf-on-aws/) and came up this with below error 
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::111111111111:user/temitayo is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<111111111111>:role/seedfarmer-addf-toolchain-role

**To Reproduce**
git clone https://github.com/awslabs/autonomous-driving-data-framework.git 
pip install -r requirements.txt
cp -R manifests/example-dev manifests/demo
source ./scripts/setup-secrets-example.sh
./scripts/setup-secrets-dockerhub.sh
seedfarmer apply ./manifests/demo/deployment.yaml

I also tried with release 1.2.1 and received a similar error

**Comment by srinivasreddych** [comment]
Hello Tayo. Thanks for reaching out. I will follow up offline.

**Comment by srinivasreddych** [comment]
Hello Tayo. As per our last discussion, we were able to solve the error you've mentioned in the issue. Closing this one here. Feel free to reach out if you have any other issues

**Comment by mehtaparitosh** [comment]
Faced a similar error but like this:

`
[2023-10-16 04:13:33,248 | INFO | session_manager.py:147 | MainThread ] Creating toolchain session
[2023-10-16 04:13:33,531 | INFO | _deployment_commands.py:306 | MainThread ] Priming Accounts
[2023-10-16 04:13:33,532 | INFO | _deployment_commands.py:310 | ThreadPoolExecutor-0_0 ] Priming Acccount 4885264XXX in us-east-1
[2023-10-16 04:13:33,532 | INFO | session_manager.py:117 | ThreadPoolExecutor-0_0 ] Creating Session for 4885264XXX-us-east-1
.
.
.
.
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::044313633XXX:assumed-role/seedfarmer-addf-toolchain-role/toolchainrole is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::4885264XXX:role/seedfarmer-addf-deployment-role
`

My account number is 044313633XXX, however ADDF was picking up this account number: 4885264XXX as the primary. I have no idea where it comes from. 

To resolve the issue, just go in the main directory and create a `.env` file with the contents:

`PRIMARY_ACCOUNT=044313633XXX`
