### ISSUE TITLE
[FEATURE] Update MLOPs on EKS to use EKS v1.29

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#449]
**Is your feature request related to a problem? Please describe.**
IDF has released support for EKS 1.29 including some very useful new features including GPU AMI support and new CSI installations. 

**Describe the solution you'd like**
Update the MLOPs on EKS deployment under `manifests/mlops` to use the newer node with proper GPU Optimized AMI support.

**Comment by dgraeber** [comment]
@a13zen Are you referring to the mlops/* that deploy Kubeflow?

**Comment by srinivasreddych** [comment]
Agreed. Started refactoring [mlops](https://github.com/awslabs/autonomous-driving-data-framework/tree/main/manifests/mlops) solution to use EKS 1.29 version
