### ISSUE TITLE
[on hold] EKS based Ubuntu Desktop + NiceDCV using Kubectl port forwarding

### ISSUE THREAD

**Issue by a13zen** [awslabs/autonomous-driving-data-framework#45]
@srinivasreddych adding more context:

AV/ADAS customers need to visualize sensor data collected in the vehicle. This includes the ability to visualize camera, LiDaR 3D Point Cloud, map and other raw sensor data. 

Customers use ROS visualization tools, such as Foxglove Studio, to do this. We've built a solution that allows streaming ROS bag files from s3 directly to Foxglove Studio. However, the problem is that streaming these files via the internet is not ideal.

We need a solution that allows deploying a visualization developer instance into a VPC and having the bag files streamed via S3 Gateway endpoints instead. This instance should use NiceDCV to allow connecting to the Desktop + have all the required ROS tooling and Foxglove studio installed (Ubuntu required).

We have a module that allows spinning up exactly such an EC2 instance (https://github.com/awslabs/autonomous-driving-data-framework/tree/release/1.0.0-reinvent/modules/visualization/dev-instance). However, again EC2 is not ideal since we want to be able to create and destroy these visualization development instances on demand (potentially from a UI). For this we are looking to replicate the dev-instance module above on EKS instead, with PODs that deploy Ubuntu Desktop + NiceDCV & Foxglove Studio on demand and can be created and destroyed on demand.

**Comment by dgraeber** [comment]
Why port-fowarding?   Wouldn't exposing an ingress and giving browse capability do the same (self-signed certs with challenge-auth)?

**Comment by dgraeber** [comment]
I ran into significant issues getting the combination of Ubuntu image with NVIDIA and OpenGL installed with  the desktop and running with virtual NiceDCV sessions (console sessions not supported with GPU).  I will need a proper image (Dockerfile) with the following defined to move forward:

- Ubuntu 20.04 Server with ubuntu-desktop
- NiceDCV with GL support and Virtual Sessions configured to use the Xserver
- proper NVIDIA toolkit installed that marries the Xsrver and OpenGL functionality 

We have aligned the deployment on a GPU compute instance in EKS, but the ran into issues as denoted above.

**Comment by JunjieTang-D1** [comment]
Do we have some update to create the proper dockerfile?

**Comment by dgraeber** [comment]
We will need support to create a docker image with the following:
Support for Ubuntu 20.04 Desktop running on GPU to leverage OpenGL.  The image should leverage nicedcv over virtual sessions (not console) in order to take advantage of the GPU.  We have vetted the support to create GPU compute resources with proper labeling for isolation (Fargate does not support EKS GPU nodes).

**Comment by dgraeber** [comment]
Reference this for an image:  https://www.ni-sp.com/nice-dcv-in-containers/

**Comment by JunjieTang-D1** [comment]
WIll the re:Invent pull request solve this issue? @dgraeber  @a13zen

**Comment by a13zen** [comment]
No, that was using EC2, this is for EKS based solution. We have de-prioritized this until after the next release.

**Comment by qvacua** [comment]
* We need someone who can provide or create an Ubuntu image which can leverage the GPU or we have to invest research time.
* We should also think about whether we really need this

**Comment by qvacua** [comment]
Will be re-opened when relevant again.
