### ISSUE TITLE
[BUG] Getting validation error during deployment of  'ros-image-demo' (fix added)

### ISSUE THREAD

**Issue by mehtaparitosh** [awslabs/autonomous-driving-data-framework#49]
**Describe the bug**
I was trying to deploy the 'ros-image-demo' deployment, and during deployment I was getting a validation error for creation of a dag role. I checked and it seems that the length of the role name created at [line 135](https://github.com/awslabs/autonomous-driving-data-framework/blob/main/modules/analysis/rosbag-image-pipeline/stack.py#L135) exceeds the maximum length of 64 characters.

I altered the length of the name of the role, however I start getting an error that the resource already existed. It seems like this dag role is being created twice in the stack (in different templates), thus to resolve the issue, I commented out [line 150](https://github.com/awslabs/autonomous-driving-data-framework/blob/main/modules/analysis/rosbag-image-pipeline/stack.py#L150). Once done, the deployment succeeds without any issues.

**To Reproduce**
Deploy the  'ros-image-demo' deployment till you get a validation error in one of the stacks where the name of a role exceeds the max character length of 64 characters 

**Expected behavior**
The deployment should have succeeded without errors . 

**Screenshots**
<img width="863" alt="Screenshot 2022-10-16 at 3 40 33 PM" src="https://user-images.githubusercontent.com/18036235/196147496-375e5dd3-a474-4f5d-a9f2-d678bf68b767.png">

**Additional context**

**Comment by kevinsoucy** [comment]
Hi @mehtaparitosh  - thanks for raising this. I refactored the manifest a bit to shorten the name lengths - this should resolve your issue. 
https://github.com/awslabs/autonomous-driving-data-framework/pull/57

**Comment by JunjieTang-D1** [comment]
can we close this bug?
