### ISSUE TITLE
Resizing Images before lane detection [FEATURE]

### ISSUE THREAD

**Issue by mehtaparitosh** [awslabs/autonomous-driving-data-framework#53]
**Is your feature request related to a problem? Please describe.**
When the running ADDF for the deployment 'ros-image-demo' with sample bag files, I get a similar error to [this github issue](https://github.com/hustvl/YOLOP/issues/63) during **lane detection**. The proposed solution was to resize images. 

<img width="1176" alt="Screenshot 2022-10-17 at 3 52 53 PM" src="https://user-images.githubusercontent.com/18036235/198122689-39f742d4-3ace-4af0-9663-3bf71db2e34f.png">

To test the solution, I resized the images to the resolution 1280x720 using a custom python script. Then I re-ran the sagemaker processing job by cloning it, but giving it a different source S3 uri. 

The sagemaker job succeeded with the new image size and got proper results in terms of lane detection (see attached images)

![frame_0144847_1608161582_350953743](https://user-images.githubusercontent.com/18036235/198122720-d90e5f8d-1e5e-44f9-9a16-4c5959bc1fe4.png)
![frame_0144836_1608161581_800930781](https://user-images.githubusercontent.com/18036235/198122726-2b29b992-b6de-405f-a7e7-76decacb178b.png)

**Describe the solution you'd like**
I resized the images to 1280x720 in a separate python script, I'm however not sure how to have ADDF do it by default before running the lane detection script.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by kevinsoucy** [comment]
I will take a look at this today
