### ISSUE TITLE
[BUG] Deployment failure: demo-integration-eks-os/eks-to-opensearch module

### ISSUE THREAD

**Issue by serge-dolgavin-dxc** [awslabs/autonomous-driving-data-framework#579]
**Describe the bug**
demo-integration-eks-os failed during deployment.

Modules list:
Modules deployed that are up to date (will not be changed): demo            
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Account ┃ Region    ┃ Deployment ┃ Group       ┃ Module                  ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ primary │ eu-west-1 │ demo       │ optionals   │ networking              │
│ primary │ eu-west-1 │ demo       │ optionals   │ datalake-buckets        │
│ primary │ eu-west-1 │ demo       │ replication │ replication             │
│ primary │ eu-west-1 │ demo       │ core        │ mwaa                    │
│ primary │ eu-west-1 │ demo       │ core        │ metadata-storage        │
│ primary │ eu-west-1 │ demo       │ core        │ opensearch              │
│ primary │ eu-west-1 │ demo       │ core        │ eks                     │
│ primary │ eu-west-1 │ demo       │ core        │ batch-compute           │
│ primary │ eu-west-1 │ demo       │ core        │ efs                     │
│ primary │ eu-west-1 │ demo       │ examples    │ example-dags            │
│ primary │ eu-west-1 │ demo       │ examples    │ docker-build            │
│ primary │ eu-west-1 │ demo       │ rosbag      │ rosbag-webviz           │
│ primary │ eu-west-1 │ demo       │ simulations │ k8s-managed-simulations │
│ primary │ eu-west-1 │ demo       │ simulations │ batch-managed           │
└─────────┴───────────┴────────────┴─────────────┴─────────────────────────┘
Modules scheduled to be deployed (created or updated): demo                                                   
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Account ┃ Region    ┃ Deployment ┃ Group       ┃ Module           ┃ Path                                   ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ primary │ eu-west-1 │ demo       │ integration │ eks-os           │ modules/integration/eks-to-opensearch/ │
│ primary │ eu-west-1 │ demo       │ integration │ opensearch-proxy │ modules/demo-only/opensearch-proxy/    │
│ primary │ eu-west-1 │ demo       │ integration │ rosbag-ddb-to-os │ modules/integration/ddb-to-opensearch/ │
│ primary │ eu-west-1 │ demo       │ integration │ emrlogs-to-os    │ modules/integration/emr-to-opensearch/ │
│ primary │ eu-west-1 │ demo       │ ide         │ jupyter-hub      │ modules/demo-only/jupyter-hub/         │
│ primary │ eu-west-1 │ demo       │ ide         │ emrstudio-on-eks │ modules/beta/emrstudio-on-eks/         │
└─────────┴───────────┴────────────┴─────────────┴──────────────────┴────────────────────────────────────────┘

**To Reproduce**
To reproduce the behavior use the following documentation: https://github.com/awslabs/autonomous-driving-data-framework/blob/main/docs/deployment_guide.md

1. git clone --origin upstream --branch main https://github.com/awslabs/autonomous-driving-data-framework
2. ...

**Expected behavior**
eks-to-opensearch deployed without issues

**Screenshots**
na

**Additional context**
$ seedfarmer apply ./manifests/demo/deployment.yaml
...
These modules had errors deploying
 demo-integration-eks-os
...

Build log:
...
[Container] 2024/09/03 09:23:58.404900 Running command cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json
--
529 |  
530 | NOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)
531 |  
532 | 25714   (cli) cdk deploy fails when stacks or stages share assets
533 |  
534 | Overview: A single asset used in two stacks or stages that depend on
535 | each other causes 'cdk deploy' to exit early.
536 |  
537 | Affected versions: cli: >=2.80.0 <2.83.1
538 |  
539 | More information at: https://github.com/aws/aws-cdk/issues/25714
540 |  
541 |  
542 | If you don’t want to see a notice anymore, use "cdk acknowledge <id>". For example, "cdk acknowledge 25714".
543 | This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
544 | (Cloud assembly schema version mismatch: Maximum schema version supported is 32.0.0, but found 36.0.0)
545 |  
546 | [Container] 2024/09/03 09:24:10.243686 Command did not exit successfully cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json exit status 1
547 | [Container] 2024/09/03 09:24:10.250256 Phase complete: BUILD State: FAILED_WITH_ABORT
548 | [Container] 2024/09/03 09:24:10.250275 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json. Reason: exit status 1

**Comment by dgraeber** [comment]
@srinivasreddych @malachi-constant I believe this is due to a mismatch in the deployspec and the CLI referenced in the requirements.in ?

**Comment by malachi-constant** [comment]
Yea I'll fix this.

**Comment by serge-dolgavin-dxc** [comment]
Sorry, @LeonLuttenberger, still the same issue:

[2024-09-04 09:16:56,597 | ERROR | _deployment_commands.py:363 | MainThread ] At least one module failed to deploy...exiting deployment
These modules had errors deploying
 demo-integration-eks-os


[Container] 2024/09/04 07:11:46.139622 Running command cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json
--
529 |  
530 | NOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)
531 |  
532 | 25714   (cli) cdk deploy fails when stacks or stages share assets
533 |  
534 | Overview: A single asset used in two stacks or stages that depend on
535 | each other causes 'cdk deploy' to exit early.
536 |  
537 | Affected versions: cli: >=2.80.0 <2.83.1
538 |  
539 | More information at: https://github.com/aws/aws-cdk/issues/25714
540 |  
541 |  
542 | If you don’t want to see a notice anymore, use "cdk acknowledge <id>". For example, "cdk acknowledge 25714".
543 | This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
544 | (Cloud assembly schema version mismatch: Maximum schema version supported is 32.0.0, but found 36.0.0)
545 |  
546 | [Container] 2024/09/04 07:11:57.589620 Command did not exit successfully cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json exit status 1
547 | [Container] 2024/09/04 07:11:57.598847 Phase complete: BUILD State: FAILED_WITH_ABORT
548 | [Container] 2024/09/04 07:11:57.598868 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json. Reason: exit status 1


Please be aware that the affected module is demo-integration-eks-os/eks-to-opensearch, not emr-to-opensearch.

**Comment by serge-dolgavin-dxc** [comment]
Please validate **emrstudio-on-eks**. It may have the same issue like **eks-to-opensearch**.

[Container] 2024/09/04 10:14:54.606917 Running command cdk deploy --require-approval never --progress events --app "python app.py" --outputs-file ./cdk-exports.json addf-${ADDF_DEPLOYMENT_NAME}-${ADDF_MODULE_NAME}-rbac

NOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)

25714   (cli) cdk deploy fails when stacks or stages share assets

    Overview: A single asset used in two stacks or stages that depend on
              each other causes 'cdk deploy' to exit early.

    Affected versions: cli: >=2.80.0 <2.83.1

    More information at: https://github.com/aws/aws-cdk/issues/25714

**Comment by LeonLuttenberger** [comment]
Hey. Sorry about that. I'm fixing the dependencies for `eks-to-opensearch` and `emrstudio-on-eks` now.

**Comment by serge-dolgavin-dxc** [comment]
@LeonLuttenberger ,

thank you for fixing the issue.

Unfortunately, I got the following error during emrstudio-on-eks deployment:
...
addf-demo-ide-emrstudio-on-eks | 15/21 | 7:17:44 AM | CREATE_FAILED        | AWS::EMR::StudioSessionMapping     | addf-demo-ide-emrstudio-on-eks-StudioSM (addfdemoideemrstudiooneksStudioSM) Resource handler returned message: "IdentityName is invalid. (Service: AWSEditors; Status Code: 400; Error Code: InvalidRequestException; Request ID: xxxxxxxxxxxxxxxxxxxx; Proxy: null) (Service: Emr, Status Code: 400, Request ID: xxxxxxxxxxxxxxxx)" (RequestToken: xxxxxxxxxxxxxxxxx, HandlerErrorCode: NotFound)
...

...

**Comment by LeonLuttenberger** [comment]
Hey,

I was able to deploy this module. Based on the error you got, it seems like the user set in the `sso-username` parameter doesn't exist in your identity center (or maybe doesn't have the right permissions?). Can you confirm that your user exists?

**Comment by serge-dolgavin-dxc** [comment]
@LeonLuttenberger ,

it appears that my sso role has admin access rights (allow all, but DenyCreateUser). I am able to deploy 18 ADDF modules except jupyter-hub and emrstudio-on-eks. 

I have bootstrapped CDK and ADDF demo project end of the last month. Is it an issue?

**Comment by serge-dolgavin-dxc** [comment]
@LeonLuttenberger ,

are you referring to  the `sso-user` parameter in ide-modules.yaml file?
Sorry, I have overlooked it.

I changed the value 
```
 - name: sso-username
   value: replace-me
```

to my SSO role name, but got the same error message as above. I used ARM and just the user name with the same deployment result.

Could you give me an advice how to solve this issue?

**Comment by LeonLuttenberger** [comment]
Hey,

Is the SSO role defined in the IAM Identify Center? We've outlined the requirements for this module in our [README](https://github.com/awslabs/autonomous-driving-data-framework/tree/main/modules/beta/emrstudio-on-eks#description).


> I have bootstrapped CDK and ADDF demo project end of the last month. Is it an issue?

I don't think it should be, as long as you're referencing the most recent version of this module.

**Comment by serge-dolgavin-dxc** [comment]
@LeonLuttenberger ,

I am using the same `AWSReservedSSO_xxx` admin role to access AWS and as the `sso-username` parameter.

**Comment by LeonLuttenberger** [comment]
Hey. Can you please share the CodeBuild logs for this module deployment?

**Comment by serge-dolgavin-dxc** [comment]
@LeonLuttenberger ,
please find the attached CodeBuild log for demo-ide-emrstudio-on-eks module. 
[emrstudio-on-eks_CodeBuild.log](https://github.com/user-attachments/files/16927930/emrstudio-on-eks_CodeBuild.log)

**Comment by LeonLuttenberger** [comment]
Hey,

Unfortunately I have not been able to replicate this issue on my end. I had the role created in the IAM Identity Center and referenced it in the manifest. I suspect your error is either due to a quirk in how your role is set up (maybe with IdP?) or an error with OIDC on the EKS cluster.

> An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name 

AWSServiceRoleForAmazonEMRContainers has been taken in this account, please try a different suffix.
This error shouldn't matter. If `AWSServiceRoleForAmazonEMRContainers` doesn't exist, the module creates it. If it does exist, it logs the error and then proceeds with the rest of the module creation.
