### ISSUE TITLE
[BUG] Python3.7 runtime is no longer supported, but used for AWS Lambda functions

### ISSUE THREAD

**Issue by serge-dolgavin-dxc** [awslabs/autonomous-driving-data-framework#580]
**Describe the bug**
Deployment of modules with Lambda functions with Python3.7 runtime not possible

e.g. emrlogs-to-os module, etc.

**To Reproduce**
Deploy modules with Lambda functions with Python3.7 runtime

**Expected behavior**
Deployment of ADDF demo works well

**Screenshots**
na

**Additional context**
Build log
...
addf-demo-integration-emrlogs-to-os | 9:25:37 AM | CREATE_FAILED        | AWS::Lambda::Function         | BucketNotificationsHandler...
Resource handler returned message: "The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions.
...

**Comment by dgraeber** [comment]
@LeonLuttenberger @malachi-constant @srinivasreddych I believe this is due to older modules referencing a CDK older than 2.82 (i.e 2.20.0) ?  The byproduct may be the older references to the python runtime....
