### ISSUE TITLE
[BUG] Module deployment failure: jupyter-hub

### ISSUE THREAD

**Issue by serge-dolgavin-dxc** [awslabs/autonomous-driving-data-framework#583]
**Describe the bug**

addf-demo-ide-jupyter-hub deployment failure, due to no longer supported runtime.

**To Reproduce**
deploy jupyter-hub module

**Expected behavior**
jupyter-hub deployed without issues

**Screenshots**
na

**Additional context**
...
Failed resources:
addf-demo-ide-jupyter-hub | 10:17:07 AM | CREATE_FAILED        | AWS::Lambda::Function                 | AWSCDKCfnUtilsProviderCustomResourceProvider/Handler 
 handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, 

 ❌  addf-demo-ide-jupyter-hub failed: Error: The stack named addf-demo-ide-jupyter-hub failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
...

**Comment by malachi-constant** [comment]
@serge-dolgavin-dxc 

You can try this before merge, I need to test from the groundup so this may take awhile before its merged.

File: `ide-modules.yaml`
```yaml
name: jupyter-hub
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/demo-only/jupyter-hub?ref=chore/583&depth=1
```

**Comment by serge-dolgavin-dxc** [comment]
@malachi-constant , 

unfortunately, 
```
name: jupyter-hub
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/demo-only/jupyter-hub?ref=chore/583&depth=1
```
doesn't work for me:

```
$ seedfarmer apply ./manifests/demo/deployment.yaml --dry-run
...
[2024-09-05 07:10:17,386 | INFO | _deployment_commands.py:636 | MainThread ]  Verifying all modules in ide for deploy 
Traceback (most recent call last):
...
  cmdline: git pull -v -- origin chore/583
  stderr: 'fatal: couldn't find remote ref chore/583'

During handling of the above exception, another exception occurred:
...
.../autonomous-driving-data-framework/.venv/lib/python3.8/site-packages/seedfarmer/mgmt/git_support.py", line 79, in clone_module_repo
    raise InvalidConfigurationError(f"\n Cannot Clone Repo: {ge} {messages.git_error_support()}")
seedfarmer.errors.seedfarmer_errors.InvalidConfigurationError: 
 Cannot Clone Repo: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin chore/583
  stderr: 'fatal: couldn't find remote ref chore/583' 
    1. Make sure your path to the repo is correct and valid (check your module manifests!)
    2. The credentials used to call SeedFarmer have access to the repo
    3. The credentials used to call SeedFarmer have not expired
```

**Comment by serge-dolgavin-dxc** [comment]
@malachi-constant ,

with
```
name: jupyter-hub
path: modules/demo-only/jupyter-hub/
```
I got the following error:

...
addf-demo-ide-jupyter-hub \|  4/11 \| 7:17:32 AM \| CREATE_IN_PROGRESS   \| Custom::AWSCDK-EKS-KubernetesResource \| addf-demo-ide-jupyter-hub-eks-cluster/manifest-jupyter-hub-namespace/Resource/Default (addfdemoidejupyterhubeksclustermanifestjupyterhubnamespaceXXXXXXXXXXXX) Resource creation Initiated
--
1321 | addf-demo-ide-jupyter-hub \|  4/11 \| 7:17:33 AM \| CREATE_FAILED        \| Custom::AWSCDK-EKS-KubernetesResource \| addf-demo-ide-jupyter-hub-eks-cluster/manifest-jupyter-hub-namespace/Resource/Default (addfdemoidejupyterhubeksclustermanifestjupyterhubnamespaceXXXXXXXX) Received response status [FAILED] from custom resource. Message returned: Error: b'\nAn error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::XXXXXXXXX:assumed-role/addf-demo-ide-jupyter-hub-HandlerServiceRoleXXXXXXXXXXXXXXX/addf-demo-ide-jupyter-hub-addfdemo-HandlerXXXXXXXXXXXX is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXXXXXXXXXXXX:role/addf-demo-core-eks-clusterCreationRoleXXXXXXXXXXX\nUnable to connect to the server: getting credentials: exec: executable aws failed with exit code 255\n'
...

**Comment by serge-dolgavin-dxc** [comment]
@malachi-constant ,

please find the attached the codebuild log  for jupyter-hub module: [jupyter-hub_CodeBuild.log](https://github.com/user-attachments/files/16927456/jupyter-hub_CodeBuild.log)

**Comment by malachi-constant** [comment]
@serge-dolgavin-dxc Can you try this module from `main` that branch was deleted after merge

**Comment by serge-dolgavin-dxc** [comment]
@malachi-constant ,

Sorry that me messages are not clear and for confusion.

I have recognized that the branch was deleted and I am already using `main` for the last 5 days.

The yesterday's codebuild log for  jupyter-hub module is based of the recent `main` branch.

**Comment by malachi-constant** [comment]
Gotcha missed that, taking a look...

**Comment by malachi-constant** [comment]
@serge-dolgavin-dxc Are you able to provide the trust policy for `arn:aws:iam::XXXXXXXXXXXXX:role/addf-demo-core-eks-clusterCreationRoleXXXXXXXXXXX\` with account values sanitized as well so I compare to what I have tested? I am not able to replicate.

**Comment by serge-dolgavin-dxc** [comment]
@malachi-constant , please find the attached policy details along with the latest codebuild log.
[jupyter-hub.zip](https://github.com/user-attachments/files/16962416/jupyter-hub.zip)

**Comment by malachi-constant** [comment]
Ok so the trust is not being added for some reason, can you also tell me which version of the eks module is deployed?

**Comment by serge-dolgavin-dxc** [comment]
I am using the latest main branch (default demo / example-dev manifests).

```
name: eks
path: git::https://github.com/awslabs/idf-modules.git//modules/compute/eks?ref=release/1.11.0
dataFiles:
  - filePath: git::https://github.com/awslabs/idf-modules.git//data/eks_dockerimage-replication/versions/1.29.yaml?ref=release/1.11.0
  - filePath: git::https://github.com/awslabs/idf-modules.git//data/eks_dockerimage-replication/versions/default.yaml?ref=release/1.11.0
```

**Comment by malachi-constant** [comment]
Ok thanks, was able to replicate, working on it...

**Comment by malachi-constant** [comment]
@serge-dolgavin-dxc 

See manifest in [PR](https://github.com/awslabs/autonomous-driving-data-framework/pull/590) 

This error is resolved by updating `ide-modules.yaml`
```yaml
name: jupyter-hub
path: modules/demo-only/jupyter-hub/
parameters:
 - name: eks-cluster-admin-role-arn
   valueFrom:
     moduleMetadata:
       group: core
       name: eks
       key: EksClusterMasterRoleArn
```

**Comment by dgraeber** [comment]
@serge-dolgavin-dxc 

I think your credentials for kubectl are pointing to the wrong cluster (do you have multiple clusters defined in .kube?)...this command:
`kubectl get ing jupyterhub -n jupyter-hub -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"`
Should be executed against the proper cluster...
REF: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by serge-dolgavin-dxc** [comment]
@dgraeber , thanks a lot for your hint! 

addf-demo-core-eks-cluster configuration was missing. 

The first issue was solved, but the second still remain. Is it an issue with access rights?
