### ISSUE TITLE
[BUG] sensorextraction/ros-to-parquet module failing at run time due to requests lib not installed

### ISSUE THREAD

**Issue by BDFurlong** [awslabs/autonomous-driving-data-framework#62]
**Describe the bug**
requests lib is missing from requirements.txt in ros-to-parquet module at autonomous-driving-data-framework/modules/sensor-extraction/ros-to-parquet/src/main.py. This is causing the batch job to fail at runtime with the following error:

**To Reproduce**
 - deploy ros-image-demo
 - run airflow job
 - sensor-extraction.parquet-extraction-batch-job fails
 - view aws batch job logs

-----------------------------------------------------------------------------
|       @timestamp        |                    @message                     |
|-------------------------|-------------------------------------------------|
| 2022-11-04 18:18:21.649 | Traceback (most recent call last):              |
| 2022-11-04 18:18:21.649 |   File "main.py", line 24, in <module>          |
| 2022-11-04 18:18:21.649 |     import requests                             |
| 2022-11-04 18:18:21.649 | ModuleNotFoundError: No module named 'requests' |
-----------------------------------------------------------------------------
**Expected behavior**
- Module does not error and successfully converts ros topics to parquet.

**Comment by srinivasreddych** [comment]
PR is merged
